export const LAYERED_SPRITES = {
  body: {
    front: {
      idle: [
        "                ",
        "     KSSSSK     ",
        "    KSSSSSSK    ",
        "    KSSSSSSK    ",
        "    KSKSSKSK    ",
        "    KSKSSKSK    ",
        "     KSSSSK     ",
        "   KKKSSSSKKK   ",
        "  KSKSSSSSSSSK  ",
        " KSKSSSSSSSSSSK ",
        " KSKSSSSSSSSSSK ",
        " KKKSSSSSSSSKKK ",
        "  KKSSSSSSSSKK  ",
        "    SSSSSSSS    ",
        "    KSK  KSK    ",
        "   KKK    KKK   "
      ],
      walk1: [
        "                ",
        "     KSSSSK     ",
        "    KSSSSSSK    ",
        "    KSSSSSSK    ",
        "    KSKSSKSK    ",
        "    KSKSSKSK    ",
        "     KSSSSK     ",
        "   KKKSSSSKKK   ",
        "  KSKSSSSSSSSK  ",
        " KSKSSSSSSSSSSK ",
        " KKSSSSSSSSSSSK ",
        " K SSSSSSSSSKKK ",
        " KKSSSSSSSSKK   ",
        "    SSSSS       ",
        "    KSK KKK     ",
        "   KKK          "
      ],
      walk2: [
        "                ",
        "     KSSSSK     ",
        "    KSSSSSSK    ",
        "    KSSSSSSK    ",
        "    KSKSSKSK    ",
        "    KSKSSKSK    ",
        "     KSSSSK     ",
        "   KKKSSSSKKK   ",
        "  KSKSSSSSSSSK  ",
        " KSKSSSSSSSSSSK ",
        " KSKSSSSSSSSSSK ",
        " KKKSSSSSSSSSSK ",
        "    KKSSSSSSSSK ",
        "       SSSSS    ",
        "     KKK KSK    ",
        "          KKK   "
      ]
    },
    back: {
      idle: [
        "                ",
        "     KSSSSK     ",
        "    KSSSSSSK    ",
        "    KSSSSSSK    ",
        "    KSSSSSSK    ",
        "    KSSSSSSK    ",
        "     KSSSSK     ",
        "   KKKSSSSKKK   ",
        "  KSKSSSSSSSSK  ",
        " KSKSSSSSSSSSSK ",
        " KSKSSSSSSSSSSK ",
        " KKKSSSSSSSSKKK ",
        "  KKSSSSSSSSKK  ",
        "    SSSSSSSS    ",
        "    KSK  KSK    ",
        "   KKK    KKK   "
      ],
      walk1: [
        "                ",
        "     KSSSSK     ",
        "    KSSSSSSK    ",
        "    KSSSSSSK    ",
        "    KSSSSSSK    ",
        "    KSSSSSSK    ",
        "     KSSSSK     ",
        "   KKKSSSSKKK   ",
        "  KSKSSSSSSSSK  ",
        " KSKSSSSSSSSSSK ",
        " KKSSSSSSSSSSSK ",
        " K SSSSSSSSSKKK ",
        " KKSSSSSSSSKK   ",
        "    SSSSS       ",
        "    KSK KKK     ",
        "   KKK          "
      ],
      walk2: [
        "                ",
        "     KSSSSK     ",
        "    KSSSSSSK    ",
        "    KSSSSSSK    ",
        "    KSSSSSSK    ",
        "    KSSSSSSK    ",
        "     KSSSSK     ",
        "   KKKSSSSKKK   ",
        "  KSKSSSSSSSSK  ",
        " KSKSSSSSSSSSSK ",
        " KSKSSSSSSSSSSK ",
        " KKKSSSSSSSSSSK ",
        "    KKSSSSSSSSK ",
        "       SSSSS    ",
        "     KKK KSK    ",
        "          KKK   "
      ]
    },
    side: {
      idle: [
        "                ",
        "     KSSSSK     ",
        "     KSSSSSK    ",
        "     KSSKSK     ",
        "     KSSSSK     ",
        "     KSSSSK     ",
        "      KSSK      ",
        "    KKKSSSKK    ",
        "   KSKSSSSSK    ",
        "   KSKSSSSSK    ",
        "   KSKSSSSSK    ",
        "   KKKSSSSSK    ",
        "    KKSSSSKK    ",
        "     SSSSS      ",
        "     KSK KSK    ",
        "    KKK  KKK    "
      ],
      walk1: [
        "                ",
        "     KSSSSK     ",
        "     KSSSSSK    ",
        "     KSSKSK     ",
        "     KSSSSK     ",
        "     KSSSSK     ",
        "      KSSK      ",
        "    KKKSSSKK    ",
        "   KSKSSSSSK    ",
        "   KSKSSSSSK    ",
        "   KKKSSSSSK    ",
        "   K SSSSSSK    ",
        "   KKSSSSS K    ",
        "    SSSSS       ",
        "    KSK KKK     ",
        "   KKK          "
      ],
      walk2: [
        "                ",
        "     KSSSSK     ",
        "     KSSSSSK    ",
        "     KSSKSK     ",
        "     KSSSSK     ",
        "     KSSSSK     ",
        "      KSSK      ",
        "    KKKSSSKK    ",
        "   KSKSSSSSK    ",
        "   KSKSSSSSK    ",
        "   KSKSSSSSK    ",
        "   KKKSSSSSK    ",
        "     KKSSSK     ",
        "      SSSSS     ",
        "     KKK KSK    ",
        "          KKK   "
      ]
    }
  },
  hair: {
    front: [
      "      KKKK      ",
      "     KLLLLK     ",
      "    KLLLLLLK    ",
      "    KLLLLLLK    ",
      "                ",
      "                ",
      "                ",
      "                ",
      "                ",
      "                ",
      "                ",
      "                ",
      "                ",
      "                ",
      "                ",
      "                "
    ],
    back: [
      "      KKKK      ",
      "     KLLLLK     ",
      "    KLLLLLLK    ",
      "    KLLLLLLK    ",
      "    KLLLLLLK    ",
      "    KLLLLLLK    ",
      "                ",
      "                ",
      "                ",
      "                ",
      "                ",
      "                ",
      "                ",
      "                ",
      "                ",
      "                "
    ],
    side: [
      "      KKKK      ",
      "     KLLLLK     ",
      "     KLLLLLK    ",
      "     KLLL       ",
      "                ",
      "                ",
      "                ",
      "                ",
      "                ",
      "                ",
      "                ",
      "                ",
      "                ",
      "                ",
      "                ",
      "                "
    ]
  },
  scrubs: {
    front: {
      idle: [
        "                ",
        "                ",
        "                ",
        "                ",
        "                ",
        "                ",
        "                ",
        "   KKKWKWWKKK   ",
        "  KWKWWKWWKWK   ",
        " KSKWWWKWWWKSK  ",
        " KSKWWKKKWWKSK  ",
        " KKKBWWKWWCBKK  ",
        "  KKBBBKBBBKK   ",
        "    DBBBKBD     ",
        "                ",
        "                "
      ],
      walk1: [
        "                ",
        "                ",
        "                ",
        "                ",
        "                ",
        "                ",
        "                ",
        "   KKKWKWWKKK   ",
        "  KWKWWKWWKWK   ",
        " KSKWWWKWWWKSK  ",
        " KKWWWKKKWWKSK  ",
        " K BWWKWWCBKKK  ",
        " KKBBBKBBBKK    ",
        "    DBBBDK      ",
        "                ",
        "                "
      ],
      walk2: [
        "                ",
        "                ",
        "                ",
        "                ",
        "                ",
        "                ",
        "                ",
        "   KKKWKWWKKK   ",
        "  KWKWWKWWKWK   ",
        " KSKWWWKWWWKSK  ",
        " KSKWWKKKWWWKK  ",
        " KKKBCWWKWWBBK  ",
        "    KKBBBKBKK   ",
        "      KDBBBD    ",
        "                ",
        "                "
      ]
    },
    back: {
      idle: [
        "                ",
        "                ",
        "                ",
        "                ",
        "                ",
        "                ",
        "                ",
        "   KKKWWWKKK   ",
        "  KWKWWWWWKWK   ",
        " KSKWWWWWWWKSK  ",
        " KSKWWWWWWWKSK  ",
        " KKKBWWWWWCBKK  ",
        "  KKBBBBBBBKK   ",
        "    DBBBKBD     ",
        "                ",
        "                "
      ],
      walk1: [
        "                ",
        "                ",
        "                ",
        "                ",
        "                ",
        "                ",
        "                ",
        "   KKKWWWKKK   ",
        "  KWKWWWWWKWK   ",
        " KSKWWWWWWWKSK  ",
        " KKWWWWWWWWKSK  ",
        " K BWWWWWWCBKKK ",
        " KKBBBBBBBKK    ",
        "    DBBBDK      ",
        "                ",
        "                "
      ],
      walk2: [
        "                ",
        "                ",
        "                ",
        "                ",
        "                ",
        "                ",
        "                ",
        "   KKKWWWKKK   ",
        "  KWKWWWWWKWK   ",
        " KSKWWWWWWWKSK  ",
        " KSKWWWWWWWWKK  ",
        " KKKBCWWWWWWBBK ",
        "    KKBBBBBBKK  ",
        "      KDBBBD    ",
        "                ",
        "                "
      ]
    },
    side: {
      idle: [
        "                ",
        "                ",
        "                ",
        "                ",
        "                ",
        "                ",
        "                ",
        "    KKKWWWKK    ",
        "   KWKWWWWWK    ",
        "   KSKWWWWWK    ",
        "   KSKWWWWWK    ",
        "   KKKBWWWWK    ",
        "    KKBBBBKK    ",
        "     DBBBD      ",
        "                ",
        "                "
      ],
      walk1: [
        "                ",
        "                ",
        "                ",
        "                ",
        "                ",
        "                ",
        "                ",
        "    KKKWWWKK    ",
        "   KWKWWWWWK    ",
        "   KSKWWWWWK    ",
        "   KKKWWWWWK    ",
        "   K BWWWWWK    ",
        "   KKBBBBB K    ",
        "    DBBBD       ",
        "                ",
        "                "
      ],
      walk2: [
        "                ",
        "                ",
        "                ",
        "                ",
        "                ",
        "                ",
        "                ",
        "    KKKWWWKK    ",
        "   KWKWWWWWK    ",
        "   KSKWWWWWK    ",
        "   KSKWWWWWK    ",
        "   KKKWWWWWK    ",
        "     KKBBB K    ",
        "      DBBBD     ",
        "                ",
        "                "
      ]
    }
  }
};
